const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Inventory = require("./models/Inventory");

dotenv.config();

const inventoryData = [
  {
    item: "Mathematics Textbook - Grade 8",
    category: "Books",
    location: "Hyderabad Warehouse",
    lotBatch: "BOOK-MATH-2026-01",
    age: 45,
    expiryDate: null,
    stock: 2450,
    safetyStock: 1500,
    leadTime: 10,
    openOrders: 500,
    reservedQuantity: 300,
    forecastDemand: 3200,
    status: "Normal",
  },
  {
    item: "Science Textbook - Grade 9",
    category: "Books",
    location: "Delhi Warehouse",
    lotBatch: "BOOK-SCI-2026-02",
    age: 60,
    expiryDate: null,
    stock: 1280,
    safetyStock: 1000,
    leadTime: 12,
    openOrders: 300,
    reservedQuantity: 180,
    forecastDemand: 1450,
    status: "Normal",
  },
  {
    item: "English Literature Book - Grade 10",
    category: "Books",
    location: "Bengaluru Warehouse",
    lotBatch: "BOOK-ENG-2026-01",
    age: 75,
    expiryDate: null,
    stock: 760,
    safetyStock: 900,
    leadTime: 14,
    openOrders: 250,
    reservedQuantity: 120,
    forecastDemand: 1050,
    status: "Warning",
  },
  {
    item: "Social Studies Textbook - Grade 7",
    category: "Books",
    location: "Chennai Warehouse",
    lotBatch: "BOOK-SST-2026-01",
    age: 50,
    expiryDate: null,
    stock: 1420,
    safetyStock: 1000,
    leadTime: 11,
    openOrders: 200,
    reservedQuantity: 150,
    forecastDemand: 1350,
    status: "Normal",
  },
  {
    item: "Science Lab Kit - Grade 10",
    category: "Laboratory Materials",
    location: "Warangal Warehouse",
    lotBatch: "LAB-SCI-2026-03",
    age: 25,
    expiryDate: "2027-06-30",
    stock: 320,
    safetyStock: 500,
    leadTime: 18,
    openOrders: 300,
    reservedQuantity: 100,
    forecastDemand: 780,
    status: "Warning",
  },
  {
    item: "Chemistry Experiment Set",
    category: "Laboratory Materials",
    location: "Hyderabad Warehouse",
    lotBatch: "LAB-CHEM-2026-02",
    age: 35,
    expiryDate: "2027-04-15",
    stock: 180,
    safetyStock: 250,
    leadTime: 20,
    openOrders: 150,
    reservedQuantity: 60,
    forecastDemand: 420,
    status: "Warning",
  },
  {
    item: "Physics Lab Equipment Set",
    category: "Laboratory Materials",
    location: "Delhi Warehouse",
    lotBatch: "LAB-PHY-2026-01",
    age: 90,
    expiryDate: null,
    stock: 95,
    safetyStock: 150,
    leadTime: 25,
    openOrders: 100,
    reservedQuantity: 40,
    forecastDemand: 210,
    status: "Critical",
  },
  {
    item: "School Uniform - Medium",
    category: "Uniforms",
    location: "Hyderabad Warehouse",
    lotBatch: "UNI-MED-2026-01",
    age: 30,
    expiryDate: null,
    stock: 1820,
    safetyStock: 900,
    leadTime: 15,
    openOrders: 400,
    reservedQuantity: 500,
    forecastDemand: 1400,
    status: "Normal",
  },
  {
    item: "School Uniform - Large",
    category: "Uniforms",
    location: "Chennai Warehouse",
    lotBatch: "UNI-LRG-2026-01",
    age: 40,
    expiryDate: null,
    stock: 640,
    safetyStock: 800,
    leadTime: 15,
    openOrders: 300,
    reservedQuantity: 180,
    forecastDemand: 950,
    status: "Warning",
  },
  {
    item: "Student Notebook - 200 Pages",
    category: "Stationery",
    location: "Hyderabad Warehouse",
    lotBatch: "STAT-NB-2026-04",
    age: 20,
    expiryDate: null,
    stock: 4200,
    safetyStock: 2500,
    leadTime: 7,
    openOrders: 800,
    reservedQuantity: 600,
    forecastDemand: 3500,
    status: "Normal",
  },
  {
    item: "Blue Ball Pen Pack",
    category: "Stationery",
    location: "Bengaluru Warehouse",
    lotBatch: "STAT-PEN-2026-02",
    age: 15,
    expiryDate: null,
    stock: 1850,
    safetyStock: 1200,
    leadTime: 6,
    openOrders: 400,
    reservedQuantity: 250,
    forecastDemand: 1600,
    status: "Normal",
  },
  {
    item: "Printer Paper - A4",
    category: "Stationery",
    location: "Delhi Warehouse",
    lotBatch: "STAT-PAPER-2026-03",
    age: 55,
    expiryDate: null,
    stock: 480,
    safetyStock: 700,
    leadTime: 8,
    openOrders: 500,
    reservedQuantity: 120,
    forecastDemand: 900,
    status: "Warning",
  },
  {
    item: "Student Laptop - Standard",
    category: "Devices",
    location: "Karimnagar Warehouse",
    lotBatch: "DEV-LAP-2026-01",
    age: 120,
    expiryDate: null,
    stock: 86,
    safetyStock: 150,
    leadTime: 30,
    openOrders: 100,
    reservedQuantity: 35,
    forecastDemand: 210,
    status: "Critical",
  },
  {
    item: "Interactive Classroom Tablet",
    category: "Devices",
    location: "Hyderabad Warehouse",
    lotBatch: "DEV-TAB-2026-02",
    age: 70,
    expiryDate: null,
    stock: 125,
    safetyStock: 80,
    leadTime: 25,
    openOrders: 50,
    reservedQuantity: 20,
    forecastDemand: 110,
    status: "Normal",
  },
  {
    item: "Classroom Cleaning Supplies",
    category: "Maintenance",
    location: "Chennai Warehouse",
    lotBatch: "MAIN-CLEAN-2026-03",
    age: 18,
    expiryDate: "2027-02-28",
    stock: 75,
    safetyStock: 100,
    leadTime: 5,
    openOrders: 100,
    reservedQuantity: 25,
    forecastDemand: 180,
    status: "Warning",
  },
];

const seedInventory = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("MongoDB connected.");

    await Inventory.deleteMany({});

    await Inventory.insertMany(inventoryData);

    console.log(
      `${inventoryData.length} inventory items inserted successfully.`
    );

    await mongoose.connection.close();

    console.log("MongoDB connection closed.");
  } catch (error) {
    console.error("Inventory seed error:", error);
    process.exit(1);
  }
};

seedInventory();